In [1]:
import numpy as np

s2 = np.array([[0, 0, 6, 0, 0],
               [1, 2, 0, 4, 5],
               [0, 1, 0, 0, 0],
               [9, 0, 0, 0, 0],
               [0, 0, 0, 6, 7]])

In [2]:
s2_data = np.array([6, 1, 2, 4, 5, 1, 9, 6, 7])

In [3]:
s2_row = np.array([0, 1, 1, 1, 1, 2, 3, 4, 4])

In [4]:
s2_col = np.array([2, 0, 1, 3, 4, 1, 0, 3, 4])

In [5]:
from scipy import sparse

s2_coo0 = sparse.coo_matrix(s2)
print(s2_coo0.data)
print(s2_coo0.row)
print(s2_coo0.col)

[6 1 2 4 5 1 9 6 7]
[0 1 1 1 1 2 3 4 4]
[2 0 1 3 4 1 0 3 4]


In [6]:
s2_coo1 = sparse.coo_matrix((s2_data, (s2_row, s2_col)))
print(s2_coo1.toarray())


[[0 0 6 0 0]
 [1 2 0 4 5]
 [0 1 0 0 0]
 [9 0 0 0 0]
 [0 0 0 6 7]]
