In [1]:
import numpy as np

theta = np.deg2rad(45)
R = np.array([[np.cos(theta), -np.sin(theta), 0],
              [np.sin(theta),  np.cos(theta), 0],
              [            0,              0, 1]])

print("R times the x-axis:", R @ [1, 0, 0])
print("R times the y-axis:", R @ [0, 1, 0])
print("R times a 45 degree vector:", R @ [1, 1, 0])

R times the x-axis: [0.70710678 0.70710678 0.        ]
R times the y-axis: [-0.70710678  0.70710678  0.        ]
R times a 45 degree vector: [1.11022302e-16 1.41421356e+00 0.00000000e+00]


In [2]:
S = R @ R
S @ [1, 0, 0]

array([2.22044605e-16, 1.00000000e+00, 0.00000000e+00])

In [3]:
print("R @ z-axis:", R @ [0, 0, 1])

R @ z-axis: [0. 0. 1.]


In [4]:
np.linalg.eig(R)


(array([0.70710678+0.70710678j, 0.70710678-0.70710678j,
        1.        +0.j        ]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ,
         0.        +0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j,
         0.        +0.j        ],
        [0.        +0.j        , 0.        -0.j        ,
         1.        +0.j        ]]))